version: '0.1'
services:
  jupyter-tf-ocv:
    build:
      context: 
        ./jupyter-tf-ocv
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/tf/notebooks
      - ./data:/tf/data
    env_file:
      .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]